# This is a config for E2B sandbox template.
# You can use template ID (xof9yoc0oayv5tqh6g80) or template name (SketchUI) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("SketchUI") # Sync sandbox
# sandbox = await AsyncSandbox.create("SketchUI") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('SketchUI')

team_id = "9b8424bc-6396-432d-8695-e9868cdcc79b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "SketchUI"
template_id = "xof9yoc0oayv5tqh6g80"
